
# ==============================================================================
# Project: Automated Blog Posting with Personal.AI and LinkedIn Integration
# File: [template_constants].py
# Author: Matthew David Schafer
# Date: Sept 5, 2023
# Company: VE7LTX Diagonal Thinking LTD
# ==============================================================================
# 
# Copyright (c) 2023, Matthew David Schafer, VE7LTX Diagonal Thinking LTD
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions, and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions, and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 
# 3. Neither the name of the company VE7LTX Diagonal Thinking LTD nor the names 
#    of its contributors may be used to endorse or promote products derived 
#    from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, 
# OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY 
# OF SUCH DAMAGE.




"""
AI-Powered Blog Posting Template

Instructions:
1. Replace `YOUR_LINKEDIN_CLIENT_ID` and `YOUR_LINKEDIN_CLIENT_SECRET` with your LinkedIn application's Client ID and Client Secret respectively.
   - You can find these in the 'Auth' section of your LinkedIn Developer application dashboard.
   
2. Replace `YOUR_LINKEDIN_ACCESS_TOKEN` with your LinkedIn access token.
   - This can typically be obtained after OAuth authentication with LinkedIn.

3. Replace `YOUR_PERSONAL_AI_API_KEY` with your Personal.AI API key.
   - This can be found in your Personal.AI developer/account dashboard.

Remember: Always keep your API keys and secrets confidential. Never expose them in client-side code or public repositories.

"""

# Constants
CLIENT_ID = "YOUR_LINKEDIN_CLIENT_ID"
CLIENT_SECRET = "YOUR_LINKEDIN_CLIENT_SECRET"

LINKEDIN_ACCESS_TOKEN = "YOUR_LINKEDIN_ACCESS_TOKEN"
BASE_URL = "https://api.personal.ai/v1"
PAI_API_KEY = "YOUR_PERSONAL_AI_API_KEY"

DISCLAIMER = """
Disclaimer: The contents of this post are generated by an AI. While every effort is made to ensure accuracy, any opinions or views expressed here are automated and belong to the AI. For more AI-powered content and insights, check out our website.

Thank you for reading the AI's content! Embrace the future, where AI and humans collaborate to create amazing content.

#ArtificialIntelligence #AIPowered #FutureTech #AIInsights #CollaborativeFuture #AI #Innovation
"""
